/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 25.07.2025 23:41:01

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1568;
#else
constexpr int kTensorArenaSize = 544;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,207 } };
const TfArray<1, float> quant0_scale = { 1, { 0.050558362156152725, } };
const TfArray<1, int> quant0_zero = { 1, { -20 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { -1, -2, 1, 5, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const TfArray<1, float> quant1_scale = { 1, { 0.0017798249609768391, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[4*10] = { 
  11, 62, 71, -35, -9, -59, -81, -33, 94, 23, 
  127, -33, -70, -52, -43, -74, -24, 66, -50, 6, 
  -72, 10, -81, -87, 33, -46, 69, 122, 82, -59, 
  11, 31, 11, 18, 17, -44, 94, -43, -74, -41, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 4,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0091814026236534119, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -7, -11, 8, 13, 8, 10, 12, 18, 4, -3, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00075150502379983664, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  42, -40, -24, 8, 92, 5, 108, -35, 15, -11, 20, -2, 72, 52, 20, -33, 17, -22, -18, 36, 
  -19, -30, -1, 62, 21, -49, -24, -41, -29, 6, -39, -32, 25, 15, -7, 7, -65, -21, -28, -18, 
  -12, -39, 47, 33, -17, -19, -12, 14, -15, -10, 20, 40, -8, -24, 21, -16, 22, -30, -49, -28, 
  13, -15, 45, -9, -37, 47, -32, -28, -22, 21, 57, 16, -39, -39, 10, -21, 31, -28, 47, 26, 
  -21, 58, -48, -8, -43, 47, -23, 1, -38, 17, 31, 26, -17, 23, 5, -33, -6, 69, 22, 14, 
  -28, 30, -43, 23, -11, -26, -1, 27, -36, -28, 54, 26, -16, 27, 3, -33, 53, 48, -24, -2, 
  75, 70, -44, -13, 54, 72, 14, -24, 3, -2, 33, 18, -22, 3, -1, -16, 84, -7, -2, -14, 
  30, 127, 6, 93, 17, 45, 88, -38, 121, 3, -26, 53, 73, 29, -56, 18, 21, 6, 18, 74, 
  39, 65, 36, 35, 35, 11, -36, -11, -1, 7, 28, 21, 0, -27, -30, 59, -63, 46, -33, -11, 
  31, -29, 2, 6, 58, 29, 1, 16, 42, -30, -30, 17, -23, -8, 14, -1, -32, 37, 4, 55, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0081112915650010109, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 22, 16, 5, -2, 15, 9, 16, -10, 12, -6, 8, 25, 17, -15, 2, 6, 24, 8, 0, -7, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00038119789678603411, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*207] = { 
  -5, -5, -3, 13, 3, 1, -2, -15, -1, -18, -7, -2, -20, -16, -9, 8, -2, 5, -14, -13, 7, -10, 7, -3, -19, 4, -12, -12, -15, -18, -2, -1, 3, -19, -20, 0, -15, 5, -8, -16, 0, -8, -18, -11, -19, 6, -12, 7, -17, -18, -10, -20, -1, -10, -19, 3, 9, 6, 10, 3, -1, -12, -5, -16, -9, -16, -6, -1, 8, -13, 8, -11, -20, -15, -11, -16, 3, -1, -10, 6, -4, -8, -10, -3, -11, -7, -23, -10, -20, -22, -3, -12, -16, 5, -10, -23, 7, 0, -20, -14, -10, -23, -6, 0, -12, -15, -15, -8, -17, -16, 4, -4, -8, 2, -16, 7, -15, -3, -23, -3, -1, -8, -5, 7, -22, -11, 2, -8, 5, -11, -21, -17, 7, -4, 5, -16, -8, 8, -16, -13, 18, -12, -22, -20, -16, -14, -14, -2, -19, -17, -16, 0, -14, 0, -5, -15, 3, -7, -26, -11, -5, 2, -20, -18, -16, -18, -22, -22, 0, 4, -18, -13, -14, -15, -13, 3, -1, -1, -20, -21, -8, -4, -23, -20, -9, -4, -17, -24, 0, -10, 6, -19, -7, 7, -1, -3, -19, 3, -22, -10, -14, 1, 6, -4, -5, -19, 2, 
  -23, -15, 14, 19, 6, 12, 15, 14, 17, 30, -8, 12, 5, 9, 24, -4, 28, 15, 22, -11, -2, 1, 25, 1, 21, 22, 4, 33, 5, -5, 11, 40, 31, 30, 22, 0, -9, 6, 13, -5, -5, -7, 29, 23, 20, 0, 24, -8, 9, 8, -11, 6, 10, -1, 3, -14, -12, 33, 35, -8, 5, 31, 0, 7, 5, 14, 36, -11, 30, -23, 25, 44, -6, -17, 1, 15, -7, -11, -2, 17, -3, -17, -8, 1, 9, 1, -5, -15, -1, -9, 0, 0, 11, -1, -4, 6, -10, -15, 2, -15, 3, 18, -1, -2, -10, 11, 17, -10, -4, -4, -6, -15, 21, 6, -4, 21, 7, 6, -10, -9, 7, -14, -3, -7, 12, 1, 2, 10, -13, 21, -5, -5, 13, -4, 22, 15, -9, -2, -24, 3, 45, -23, -26, -15, -7, 3, 4, 2, -12, -15, -14, -12, -13, -11, -13, 3, -1, 3, -26, -22, -25, -29, -4, -22, -29, -19, -26, -8, -24, -13, -12, -21, -2, -15, -10, 5, 3, -12, -16, -16, -17, -1, 1, 0, -9, 8, -7, -8, 6, 13, 10, 3, 9, 12, -5, 1, -11, -15, -15, 15, 12, -6, -13, 2, -10, 1, 9, 
  82, -1, -47, 9, 42, -7, 20, 27, 30, 4, -9, 15, -4, 28, -4, 22, 12, 23, 22, 41, 54, -6, 32, -5, 18, 7, 37, 23, -3, -10, -7, 19, 23, -3, 10, 1, -12, 2, 20, -7, 27, 27, -10, 3, 14, 0, -7, -14, 7, -7, 7, -8, -5, 0, 17, -11, 9, 8, 6, -3, 25, -5, -1, 5, -6, 11, 3, -11, -6, 6, -37, -22, -3, 13, 0, -13, -13, 18, -5, -7, 17, -6, 13, 1, 3, 5, -2, 9, -5, 13, -7, 27, 10, -4, 29, 19, 9, 12, 7, 5, -19, -13, -4, -10, 13, -9, 20, 18, 5, 1, -5, 16, 2, -16, -14, -19, 5, 18, -9, 5, -12, 17, 23, -18, 22, 20, 5, 14, -17, -1, 15, -11, 6, 12, 12, 12, -9, 17, 7, 45, -15, 36, 36, 19, -18, -2, -18, 0, -8, 6, 14, -9, -9, -2, 6, 22, 20, 5, 28, -12, 5, 20, 8, 24, 0, -12, -10, -6, -11, -6, -16, 1, 7, -19, -10, 1, 14, -6, -4, -14, 17, -15, 1, 26, -7, 10, 16, -2, 11, -13, 4, 11, -2, 25, 3, -13, 4, -17, -14, -1, 20, -4, -1, -9, -19, -18, 3, 
  -10, 5, -9, 6, -5, 5, -6, 12, 4, -17, 9, 9, 4, 6, 3, -8, -16, -11, 2, 8, -12, 3, -13, -9, 6, 4, -15, 5, 9, 6, -13, 1, 9, -11, 6, -2, 12, -19, -2, 7, -16, 6, -4, 9, 12, -17, -6, -15, 5, 3, -16, -6, -8, -20, -1, -17, -19, -21, -13, -8, 10, 0, 11, 7, -17, -20, 4, -19, -15, -11, 6, -16, -3, -6, -1, 1, -8, 13, 2, 12, -1, 6, 7, -8, -6, -16, -5, -9, 7, -9, 3, 2, -15, -1, 10, -9, -13, -7, 9, -8, -9, -6, 9, -13, -12, -6, -3, -9, -2, 0, -17, -2, -6, 7, -4, 10, -19, -5, 7, -6, -19, 9, -4, 0, -18, -4, -5, -14, -1, 1, -10, -18, -9, 10, -8, -12, -15, -2, 5, 16, 2, 30, 17, -9, 0, 0, -9, -14, -9, -15, -7, -13, 10, 11, -13, 2, 4, 15, -10, -14, -6, 6, 12, 8, -9, 3, -7, -13, 2, 0, -17, -9, -3, -17, 6, 3, 2, 4, 8, -18, -7, 8, 11, 10, -2, -17, -5, 7, -3, -12, -6, -15, -4, -13, -4, 12, -11, -14, -13, -11, -11, -8, -14, -11, -3, -5, -3, 
  12, 8, 9, -13, -15, -16, 12, -8, -12, 7, -9, 0, -14, -11, -15, 6, 7, 8, -5, -8, -6, 13, -7, -7, -9, -3, 9, 9, -19, -17, 5, -15, 12, -16, -9, -12, -9, -19, 0, 7, -2, 2, -18, -10, 6, -14, 10, 7, -7, 9, 8, 9, -17, -8, -9, 14, 8, 10, 12, 7, -18, -17, 13, 13, -3, 6, -11, 14, -20, -7, -8, 5, 10, 4, 4, 5, -9, -8, -12, -10, 10, -19, 5, -15, 2, -13, 0, -15, 8, -10, -10, -3, 1, 8, 2, -3, 0, -8, -16, -16, -8, -18, 1, -9, 13, -12, -19, -8, -15, 2, -14, -5, -14, -4, 3, -5, -10, -15, -13, -6, 13, -9, -13, -6, -18, -3, 13, -17, -12, 4, -9, -7, 4, -7, -8, -8, 6, 6, -17, 16, 3, 1, 8, -2, 9, -19, 10, -1, -18, -18, -6, 5, -10, -15, 5, 14, 11, -13, 12, -16, -10, 8, -18, -8, -19, -14, 0, -10, 13, -9, -8, -19, -16, 6, 6, -1, -11, 6, -10, 2, -11, -3, 2, 2, 1, -17, -12, -15, 10, -14, 11, -11, 3, -14, -11, 10, -5, -8, -3, -14, -15, 13, -2, -19, -16, -18, -7, 
  7, -4, -12, 25, 16, -7, 10, 30, -1, 11, -11, -3, -13, 16, 12, 9, -9, 14, 0, 7, -7, -7, 8, -1, 31, 6, 20, 9, 1, 39, 7, 8, 24, -5, 9, -10, 23, -3, 16, 25, 19, 12, -7, -1, 7, -13, -10, -9, 3, 18, 25, 3, 12, -2, 14, 19, 14, 5, 21, 10, 14, -10, 24, -6, 3, 10, 2, 30, 32, -8, 21, 39, -7, -33, -22, -16, -9, -9, 4, -5, -16, 1, -12, 8, -6, -15, 0, -5, 11, -9, -5, -6, -16, 5, -7, -9, -10, -2, -8, 3, -9, -3, 6, -15, -2, -2, 12, -14, 0, 3, -8, -8, -2, 2, 5, -3, 2, -16, 0, -13, -18, 5, -15, -1, -3, 12, -6, -10, -12, -19, -4, 0, -14, -9, -1, 10, 3, -14, -4, 127, 87, -20, -19, -20, -8, -19, 6, 7, 6, -15, 4, -5, -3, -23, 3, -11, -16, 2, -19, -13, -2, -29, -4, -27, -1, -30, 5, -22, -2, -9, -12, 3, -26, -11, -25, -5, -21, -13, 8, -1, 5, -3, -22, -19, -10, -16, -8, -17, 8, -21, -17, 9, 0, -6, -4, -18, 8, -8, 5, -6, -8, -1, 4, 3, -20, -18, -18, 
  5, 2, 0, -13, -14, -20, -10, 8, -11, -3, -5, -6, -4, 6, 3, -7, -12, -13, 13, 10, -13, -1, -12, 7, -12, -6, 14, -18, 10, 0, 8, -20, -4, -7, -17, 6, -19, 3, -18, 14, -6, -1, -6, -4, -13, -19, 13, -14, -6, -8, -16, 11, -19, 7, 1, -6, -3, 11, 5, -11, -15, -3, 8, -15, 4, 0, -19, 7, -17, -11, 11, 13, -4, 6, 1, 7, 4, 10, 4, -12, 9, 7, -4, 1, -14, -9, 7, 0, -12, -12, -16, 7, -11, 12, -10, -20, -12, -14, -19, -6, -14, -14, -3, -9, 13, -7, -7, -15, -13, -5, -5, 5, 8, -20, 0, -8, 6, -11, -18, -10, -13, 0, -18, -4, -11, -18, -6, 4, -9, -18, 3, -20, -6, 4, 8, 10, -17, 4, 9, 18, 3, 8, -7, -20, -16, -2, 8, -18, 10, 7, -15, 11, -5, 11, -11, -19, -1, -11, 8, -12, 13, 2, -7, -15, 7, -11, -11, 6, 9, -1, -20, 9, 7, 14, 4, -18, -20, -11, 2, -8, 8, -10, 11, -3, -12, -19, 5, -18, -16, -19, 6, -14, 8, -9, -18, -9, 7, 11, -8, -5, -14, -13, -9, -13, -6, 12, 14, 
  42, -8, -10, 35, 34, 13, 13, 16, -1, 29, 2, 34, 1, 20, -6, -12, -1, -4, -5, 40, 35, -4, -3, 9, 4, 36, 2, 16, -11, 4, 11, 30, 13, -9, 1, -11, 3, 12, 25, 0, 4, 15, 34, 32, 14, 4, 10, -11, -7, 15, -9, -2, 0, 8, -1, -6, -10, 24, 22, -13, -7, -1, 18, -8, 17, 10, 9, -4, -4, 34, -18, 4, -7, 4, 4, 9, -3, 19, -5, 18, 31, -13, 19, 3, 9, -13, 15, 18, 26, 0, 1, -11, 8, -6, -11, -5, -3, -12, 4, 26, -3, 20, 5, -11, 1, -4, -6, -13, 28, -3, -6, -11, 7, 13, 23, -7, 20, -2, -6, 12, -4, 9, 1, -11, 13, 13, -9, -11, -1, 0, 19, 3, 0, 8, -8, 19, 0, -1, 0, 18, -6, 16, 16, 20, 10, 16, 0, -13, 18, 7, 16, -7, 2, 15, 16, 8, -5, 8, 0, -5, -1, -14, 8, -2, -2, -6, -18, 11, -17, -3, 17, -3, -4, 4, -15, 15, -8, -14, -5, 0, 1, 24, -3, -7, -10, 8, 14, 21, 28, 2, -15, -2, 19, 27, -5, 10, 24, 18, -8, 11, -8, -1, -10, 4, -3, 23, -3, 
  7, 16, 16, -5, -16, 7, -6, -14, -5, -7, -3, 7, 7, -10, -1, -11, 4, -12, 14, 0, 13, 9, 13, 4, 7, 8, 9, -5, 11, -18, 6, -19, -6, -4, -17, -9, -18, 12, -15, -2, -12, -12, -19, -11, -18, 2, -10, -6, -13, 2, -19, -20, 14, -14, 5, 5, -1, 5, -6, -10, 8, -8, 12, -11, -3, -20, 12, 9, 7, -10, 0, -4, 2, -12, -9, -18, -15, -11, -13, 12, -12, -13, -16, -11, 12, 0, -5, 3, 7, 6, -4, -18, -18, -8, 10, -5, 13, 1, 4, -13, -15, -13, -11, 5, -2, 9, -8, -2, 1, -5, -11, 8, -1, 5, 10, 13, 2, -14, 11, -8, 9, 11, -3, -9, 6, -19, 0, 14, -18, 10, -19, 11, -20, -9, -15, -4, -15, 12, 2, 18, 12, -1, 10, -12, -17, -1, 4, -15, -18, -13, 12, 6, -13, -15, -12, 7, -20, -19, 7, -6, 7, -2, 0, -16, -8, -18, -17, 2, 1, 0, 12, -6, -1, 11, 12, -11, 11, -9, -20, 3, -18, -10, -15, -9, -3, 4, -16, -10, -18, 6, 6, 5, -3, 6, -17, 5, -6, -11, -18, 11, 9, 2, -9, -9, 2, -8, -1, 
  -16, 17, -11, 1, -8, 20, -13, 4, -6, -15, -12, -9, -15, -1, -8, 26, 2, 20, 21, -9, -1, 19, 7, 29, 31, 21, 5, 11, 3, 16, -4, -1, -10, 3, 22, 11, 23, 25, 1, 7, 9, 14, -6, 10, -4, -15, 22, 15, 29, -10, 20, 32, -14, -13, -7, 8, 19, 6, -13, 12, -13, -6, -9, 26, 5, 0, -13, -1, -8, 10, -2, 17, 20, 4, 1, -10, 29, -1, -15, 22, 17, 30, -12, -6, -9, 25, -9, -6, 15, 7, 25, 13, -2, 1, 6, 28, 3, -13, -10, -4, 21, -10, -12, -3, 7, 3, -15, -4, 14, 13, 16, -6, -4, -4, 29, 23, 27, 20, 23, 18, 27, -14, -5, 28, -6, 17, 24, -2, -5, 15, -4, -7, -3, -1, -12, 16, 28, 4, 7, -16, 21, -11, 8, 3, 6, 14, 30, 3, -14, 2, -14, -13, -5, -10, 29, -12, -11, 15, -12, 0, 0, -15, 14, 13, 4, -15, -3, -5, 3, -7, 8, 22, 21, -2, -13, -7, 5, -10, 23, 0, -15, 3, 18, 24, 15, -9, 31, 23, 0, 3, 6, -6, -4, 30, 7, -12, -3, -2, -14, 1, 18, 11, -8, -1, 15, 21, 24, 
  8, 17, 26, -24, -21, -4, 18, 7, 2, 11, -11, 10, 8, -12, 14, -7, 3, 3, 9, 5, -14, 12, -15, 20, 21, -2, -7, -4, 19, 19, -15, -11, -11, -2, 29, 27, -2, -11, -11, 10, 12, 1, 4, -2, -2, 24, 6, -13, 22, 16, -1, -7, 1, 3, 24, 29, -8, -4, 10, 1, 11, 14, 22, 24, 12, -14, -12, 18, 18, 6, 33, -1, 3, 0, 4, 30, 12, -7, 17, 33, -3, -8, 13, -8, -3, 24, -2, 10, -3, -5, 4, 32, 17, -6, 1, 6, -6, 14, -12, 19, 29, 22, 18, 17, 20, -4, 6, -12, 28, 8, 1, 8, 18, 22, -12, 11, 0, 32, -2, -6, -4, -11, -6, -9, 29, 19, -9, 11, 19, -12, 24, -3, -9, -13, 13, 13, 2, -12, 39, 10, -12, -8, -2, 17, 4, -11, 5, -1, 20, -2, 7, 25, 25, 36, -4, -4, -2, 11, 4, 10, 34, -9, 32, 19, 6, 11, 16, -5, 6, 9, 27, -1, -3, -10, 32, 33, 16, 7, 16, 35, 16, -11, 19, -10, 1, 24, -10, 23, 36, 8, -8, -13, 26, -13, 8, 19, 1, -4, -12, 3, 17, 32, 20, -2, 1, 25, 15, 
  -9, 14, 17, -2, -11, -9, 37, 1, 29, 4, 32, 33, 27, 37, 3, 24, 0, 0, 28, 9, 5, 6, 36, 11, 18, 21, 28, 25, 41, 25, 12, 7, 11, 1, 20, 8, -3, 19, 17, 23, 21, 30, 36, 9, 0, 5, 18, 24, -8, 10, -5, 30, 19, 19, 34, 28, 28, 11, 19, -5, 36, 30, 14, 9, 39, 36, 38, 11, 12, -19, -15, 48, -20, -20, 22, 10, 14, 23, 15, 9, 18, 31, -9, -3, -11, -12, -8, 15, 3, 21, 16, -12, -16, -13, 5, 7, 11, 16, -2, -3, 0, 1, 23, 24, 23, 16, 8, 30, 7, -9, 4, 16, 21, 18, -9, -4, -10, 10, 22, 14, 30, 27, 7, 2, 5, 1, -5, -9, 30, 23, -7, 20, 16, 3, -10, 14, -6, 30, -19, -10, 55, -12, -15, 14, 19, -13, 4, -4, -9, -4, 26, -4, 4, 6, -1, 7, 11, 26, 1, -3, 19, -6, 0, 8, -17, 7, -9, -12, 12, 2, 8, 5, 25, -5, 22, 1, 22, 25, 0, 26, -2, 26, 15, 21, -8, 15, 7, 14, 26, 21, -12, -1, 5, -11, 0, 30, 24, 25, -10, -2, 4, -8, 30, -6, -7, 20, -4, 
  -10, -10, 6, -8, 7, -18, -14, -20, -17, 4, -8, -19, 0, 5, -10, 9, -2, -10, 11, -9, 4, 6, -14, 7, 5, -9, -3, -12, 11, -9, -11, 0, -20, 12, 7, 7, 10, -15, -18, -14, -6, -2, -17, -12, -20, -11, 12, 6, -7, 14, 8, -18, -20, -1, -15, -20, -15, 1, -8, 3, -10, -16, -16, 7, -2, 0, 7, 2, -3, 8, 7, -5, 4, 8, 0, -20, -11, 9, -18, -18, -2, 3, 11, 7, 12, 9, -19, -13, -4, 6, -16, 12, -1, -1, -15, -18, 2, -3, 7, -8, -15, 6, 4, 1, -5, -17, -6, 10, 5, -2, -5, -10, -4, -12, -15, -2, -12, -10, 12, 5, 6, -6, 2, -13, 2, 3, -20, 5, -13, 11, -5, 5, 10, -5, 1, 12, 5, -5, 9, 24, 8, 0, 10, -9, -11, -9, -20, 8, -10, -20, 0, -16, -5, 1, -6, 13, -16, 6, -11, -12, 9, -9, -20, -11, -16, -19, -5, 13, -12, -13, 11, -15, -19, 1, 3, 6, -11, -1, -12, -20, -17, -9, -10, -7, 9, -16, -14, -18, -13, -16, -6, 13, -2, 6, -13, 12, -10, 1, -14, -13, -2, 4, -15, 11, -3, -18, -1, 
  -3, -10, 0, -9, 8, 10, -21, 9, -10, -3, -4, -2, 9, -2, -11, -19, -23, -10, -20, -13, -19, -20, -8, -13, -15, -23, -19, 8, -10, -6, -2, -24, -20, -23, -10, -3, 1, -9, 7, -13, 9, 1, 7, -19, 8, -15, -8, 3, 11, 4, -1, 1, -19, -15, 9, -14, -4, 5, 1, -10, -7, -13, -10, -20, 4, 6, 7, 7, -4, 16, -2, -8, 20, 4, 2, -17, -14, -13, 2, -15, -13, 1, -11, -12, 3, -4, 6, 8, -7, -21, -5, -2, -16, 3, -20, -17, -13, 10, -6, -14, -3, 9, -2, -17, -16, 1, -6, -8, -11, 1, 5, -20, -15, -1, -16, 3, 3, -15, 4, -19, -7, -12, -13, -12, 9, -3, -19, 7, 0, 8, -19, -18, -2, -7, -19, -20, 1, -12, -3, 3, 7, 6, 21, -19, -10, 6, 2, -14, 3, 10, -12, -17, -17, -17, -8, 9, -14, -8, 5, -11, -8, 6, 3, -1, -3, -3, 5, -17, -16, -11, 9, -12, 0, -1, -10, -18, -2, 6, -9, -6, 3, -17, -14, -3, -1, -1, -19, -5, 11, 5, -10, -21, 0, 3, -11, -4, -19, -9, 3, -21, -14, -5, -3, 2, 7, -1, -1, 
  3, 27, 34, -19, -20, -15, -12, 3, 6, 3, 18, -20, -19, 13, -23, -12, -19, 0, 10, -21, 8, 11, -17, 5, -25, -19, -13, -24, 2, -16, 8, -17, -14, 5, -10, -18, -19, 0, 13, -19, -21, 13, -22, 8, -7, 9, -10, -14, -19, -10, -6, 7, 6, -4, -15, -15, 13, -10, 10, -15, -4, 3, -16, 10, -5, 9, 9, 4, -10, 35, 44, -30, 50, 13, 20, 11, -9, 6, -1, 2, 12, 2, -14, -10, 6, -15, 21, 5, -16, 8, -6, 14, 2, 20, -15, 3, 21, 19, 19, 24, -17, 23, -13, 17, -17, -6, 18, -15, -6, -11, -9, 1, 26, 15, -16, 16, 23, -17, 17, 18, -10, -2, -1, -11, -13, -15, -1, 22, 21, -12, -6, -11, 0, -1, 14, 8, 16, 4, 31, 0, -31, 77, 52, -2, 29, 28, 20, -4, 23, 25, 0, -8, 29, 27, 25, 2, 10, 32, 13, 2, 37, 44, 28, 23, 3, 9, 32, 26, 34, 1, 27, 23, 1, 0, -5, 25, 30, 20, 13, 22, -14, -7, -9, 6, 11, 10, 9, 14, 29, 14, -12, 6, -7, 23, -2, -1, -14, 8, 18, 20, 25, -16, 24, -4, -14, 21, -13, 
  35, 25, -34, 1, -1, 9, 1, 7, 11, 11, 4, 16, -1, 22, 18, 22, 7, 15, 20, 33, -6, 36, -6, 23, 17, 11, 1, 3, 6, -3, 12, -1, 0, 24, 10, 13, 5, -12, 10, 27, 22, 0, 15, -7, 20, -7, -14, -4, -14, 12, 5, -4, 13, 18, 11, -5, 28, 17, -6, 25, 6, -6, 9, -2, 7, 12, 7, -5, 7, 5, -48, 45, 1, 2, 8, 15, -8, 4, 19, 9, -10, -8, 3, 19, 20, 14, 0, 12, 16, 25, -1, 20, 2, 11, 19, 12, -18, 7, 7, 5, 13, 18, 22, -4, 14, -13, 0, 7, 21, -8, 9, -13, -17, 2, 10, -14, -9, -19, -4, -5, -12, 1, -4, -7, 6, -6, -12, -10, -7, -15, -4, -6, 3, 17, -11, -6, -8, -2, -12, 24, -1, -3, -16, -7, 10, -3, 13, -4, -6, -16, 8, -9, -12, 9, 5, 1, -13, 14, -12, -20, -16, 13, -21, 5, -5, -12, -23, 6, 5, -6, -9, -10, -11, -16, 4, 14, -7, -19, -16, -5, 19, -11, -15, -12, -6, 4, -5, -10, -3, -21, -18, 11, 6, -14, 10, -15, -16, -17, 2, 4, 12, 13, -8, -11, 11, -5, 4, 
  -26, -19, 36, -18, 0, -7, -10, -17, 3, -20, -20, -12, -4, 0, -13, 2, -18, -14, -1, -18, -27, -20, -2, -17, -2, -16, -13, 5, -22, 5, 0, -6, 7, -20, -15, -17, 0, -20, -13, -6, -8, -12, -4, 9, -7, -20, 13, -20, -3, -7, 2, -2, -4, -15, -6, -22, -9, -10, 7, -17, -16, 14, -15, -3, -16, 6, -3, -10, -3, 21, 55, -23, 1, 34, 14, 9, -12, 2, -15, 0, 0, 17, -21, -7, -2, 14, -2, -16, 14, -11, -1, 21, 20, 1, 1, -12, 0, -8, 21, -9, -3, -5, -8, -7, 19, 18, 13, 22, -6, -15, 9, 3, 16, -17, -16, 10, -4, 23, -9, -15, 12, -2, -12, -3, 20, 3, -2, -16, 22, 21, -4, 17, -5, 3, -15, -3, 12, -16, 56, -28, -1, 6, 26, -1, -4, 15, 29, 20, 4, 6, -10, 0, 24, 20, 7, -1, 15, 20, -12, 3, -9, 17, 4, 27, 26, -4, 29, -11, 3, 12, 15, -5, 12, 24, 20, 2, 15, 17, -21, 21, 20, -6, -15, 11, 20, -13, -13, 16, -17, 13, 24, -19, -18, 18, 22, 15, 8, -9, -5, 9, -9, 18, -10, -3, 25, 14, -14, 
  39, -1, -6, 67, 66, 2, 1, 32, 18, 6, 1, 37, 3, 35, -4, 2, -5, 15, 41, 2, 34, 4, -3, 47, 2, -3, 2, 26, 14, -1, 8, -6, 12, 20, 15, 39, 35, -3, 27, -8, -9, 4, 37, 2, 14, -5, 6, 24, -11, 11, -7, -8, 24, 16, 12, -6, 29, -8, 4, -1, 16, -7, 21, 34, 3, 19, 5, 7, 13, -19, -11, 53, -8, -2, 9, 4, -13, -12, 16, -10, -11, -13, -13, 3, 9, 17, -7, 6, 7, 10, -1, 16, -19, -12, 10, 5, 3, -11, 12, -21, 13, 5, 1, -10, -10, -18, -15, 18, 4, -17, -15, -9, 12, -3, -16, 1, 8, 15, -12, -5, -13, 16, 3, 17, 0, 7, 6, 14, 16, 15, 8, 7, -11, 15, 1, -3, 20, 12, -18, -9, 37, -38, -37, 4, 1, -9, -3, 0, 10, -5, 4, 9, -25, -21, -3, -13, -11, 1, -1, -19, -25, -28, -29, -12, 4, 2, -28, -20, 4, -6, -26, -12, 6, 5, 4, 6, -3, -2, -9, 9, 13, 10, 12, -11, -16, 7, 14, -9, -2, -19, 7, 12, -2, 16, 13, -17, 1, 11, 3, -14, -5, -14, -3, -17, 0, -13, 3, 
  -24, -1, 23, -21, 6, 4, -9, 1, 2, -4, -14, -5, -15, -12, -12, -7, 4, -8, -10, 7, -10, 20, -10, 19, -8, -15, 0, -5, -15, -11, 13, -5, -9, -16, 25, 21, 8, -9, -11, -4, -12, 5, -9, 14, 3, -1, 30, 9, -10, -12, 6, -11, 16, -6, 20, -10, -9, -9, -2, 21, -2, -6, -9, 24, 16, -6, 27, -11, 5, 24, 32, 5, 24, -2, -14, 10, 26, 7, -3, 11, 9, 13, 26, 3, 16, 8, 26, 4, 0, -13, -15, 24, 19, -3, -10, -10, 17, 9, 30, -7, -14, 30, 8, 4, -6, 5, -5, -9, 5, 17, -9, 6, -14, -5, -5, -9, 17, 16, -11, -11, 28, -6, -1, 8, 11, 30, 0, -3, 6, 6, -12, -4, 5, 3, 1, -7, 9, 28, 0, 2, 8, -3, 1, -2, 29, 26, 12, 14, 2, 0, 3, 15, 28, 19, 6, -3, 18, -5, 30, 2, 13, -3, 15, -10, -1, -10, -3, 34, 4, 22, 28, -10, 29, 25, 4, 20, -7, -5, 21, 20, 16, -3, -12, 27, 23, -11, -13, -7, 2, 7, 3, 6, -2, -4, 8, -3, -3, -3, 21, -9, 23, -9, -1, 17, 2, -4, -6, 
  -9, 25, 12, -13, -7, -4, 7, -1, 17, 16, -13, 17, 14, -1, 0, -6, 1, -13, -10, 2, -9, -18, 16, -15, -2, 0, -12, -8, 7, 17, -11, 4, 19, -11, 0, 6, -15, 6, 2, -1, -11, -12, 5, 12, 1, -13, -15, 8, 1, 4, 9, 14, -12, 11, 12, -7, 12, -13, -10, 20, -11, 17, -10, 9, -11, 0, -1, -9, -10, -10, -1, 9, -1, 2, -2, 9, -13, -15, -14, -6, 19, 0, 1, -13, -2, 10, 22, -1, 6, 0, -16, 4, -11, -3, 8, -13, -10, -11, 26, -8, -3, 20, 17, -12, -2, 18, -14, -9, 1, 15, 25, 19, -13, -9, 13, 6, 2, -7, -5, 2, 27, 6, 12, -7, 8, 18, -13, 4, -6, 3, -10, 3, 21, 15, 5, 25, 12, 19, -5, -9, 7, -12, 8, 9, 4, 23, -10, 23, -1, 12, -15, 14, -1, -4, 5, -13, -11, -3, 1, 15, -12, -15, 21, -4, 9, -12, 19, 18, 24, -8, -4, 16, 9, -2, 7, 18, -11, 3, -10, -5, 7, -10, -4, -1, -6, 9, -11, -3, -4, 24, -4, -2, 25, 13, 4, 17, -11, -10, 24, -11, 13, -14, 7, 18, 16, 0, -7, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,207 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0075397593900561333, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.092649243772029877, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.19385109841823578, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,4 } };
const TfArray<1, float> quant9_scale = { 1, { 0.36980026960372925, } };
const TfArray<1, int> quant9_zero = { 1, { -78 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 207, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 4140, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 208), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_7_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_7_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_7_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_7_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_7_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
